#!/usr/bin/env bash
DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "$DIR/test/testlib.sh"
T="$(mktemp -d "${TMPDIR:-/tmp}/fleet-test.XXXXXX")"
export FLEET_STATUS_CMD="cat $T/tsv"
printf 'obj\t1-api\tin-review\trun reviews round 1\n' >"$T/tsv"
out="$("$DIR/bin/fleet-watch" --once --state "$T/state")"
assert_eq "$out" "obj/1-api: run reviews round 1"
out="$("$DIR/bin/fleet-watch" --once --state "$T/state")"
assert_eq "$out" ""
printf 'obj\t1-api\tin-review\tstart fix round 2\nobj\t2-ui\twaiting\tblocked on 1-api merge\n' >"$T/tsv"
out="$("$DIR/bin/fleet-watch" --once --state "$T/state")"
assert_contains "$out" "obj/1-api: start fix round 2"
assert_contains "$out" "obj/2-ui: blocked on 1-api merge"
printf 'obj\t2-ui\twaiting\tblocked on 1-api merge\n' >"$T/tsv"
out="$("$DIR/bin/fleet-watch" --once --state "$T/state")"
assert_eq "$out" "obj/1-api: gone"
export FLEET_STATUS_CMD="false"
out="$("$DIR/bin/fleet-watch" --once --state "$T/state")"
assert_eq "$out" "fleet-watch: status failed"
out="$("$DIR/bin/fleet-watch" --once --state "$T/state")"
assert_eq "$out" ""
finish_tests watch
